### ISSUE TITLE
Inaktiver handlingsanvisninger og øvrige skemaer

### ISSUE THREAD

**Issue by jk-randers** [Randers-Kommune-Digitalisering/jobs#26]
Afslutning af borger -> klik på øverste handlingsanvisning -> gem som inaktiv -> forsæt indtil alle er gemt som inaktive

```[tasklist]
### Tasks
- [x] Akutkald må ikke fjernes
- [x] Fix exception på Skemaer - afslutning af borger
- [ ] Fix 409 client error fejl
```
